### ISSUE TITLE
The Visual Studio 2022 has the guard model upside down and vanishes with mouse movement.

### ISSUE THREAD

**Issue by calva117** [emeiri/ogldev#25] opened 2023-06-14 01:46 UTC
Advanced OpenGL Tutorial – Skeletal Animations with Assimp Tutorial 28 to be specific. When I run on Windows 10 Visual Studio 2022 on a 1080p monitor, an animated upside-down guard can somewhat be seen at the edge of the window, and then completely disappears when the mouse moves. I can see the upside-down guard again if I move my mouse pointer to the bottom mid of the window, but still the guard is upside down and at the bottom of the window.

**Comment by emeiri** [comment] 2023-07-20 19:14
Unfortunately I'm unable to reproduce this problem. I assume you are running the original code. Perhaps try to decrease the resolution of the window a bit so that it will fit nicely within the monitor. You will find it at the top of tutorial28.cpp.

**Comment by emeiri** [comment] 2024-04-26 21:52
Closing this issue as there hasn't been an update. Please reopen if needed.

**Closed by emeiri** 2024-04-26 21:52 UTC
